### ISSUE TITLE
Using "ramenctl test clean" fails to remove resources when RBD images never sync

### ISSUE THREAD

**Issue by netzzer** [RamenDR/ramenctl#112]
Installed subscription-based busybox app with RBD volume using ramenctl version v0.3.5 and the status of DRPC (below) shows that "All PVCs of the VolumeReplicationGroup are not ready" and initial sync for RBD image never happens.   Attempts to use "ramenctl test clean -o ramenctl-dr-test" failed to unprotect app or delete app from primary cluster.

[ramenctl-dr-test.tar.gz](https://github.com/user-attachments/files/19708386/ramenctl-dr-test.tar.gz)

```
status:
  actionDuration: 4.406855677s
  actionStartTime: "2025-04-10T20:00:01Z"
  conditions:
  - lastTransitionTime: "2025-04-10T19:59:52Z"
    message: Initial deployment completed
    observedGeneration: 1
    reason: Deployed
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-10T19:59:52Z"
    message: Ready
    observedGeneration: 1
    reason: Success
    status: "True"
    type: PeerReady
  - lastTransitionTime: "2025-04-10T19:59:55Z"
    message: VolumeReplicationGroup (test-subscr-deploy-rbd/subscr-deploy-rbd) on
      cluster hyper3 is reporting errors (All PVCs of the VolumeReplicationGroup are
      not ready) readying workload data, retrying till DataReady condition is met
    observedGeneration: 1
    reason: Error
    status: "False"
    type: Protected
  lastUpdateTime: "2025-04-10T20:00:05Z"
  observedGeneration: 1
  phase: Deployed
  preferredDecision:
    clusterName: hyper3
    clusterNamespace: hyper3
  progression: Completed
  resourceConditions:
[...]
```

The RBD issue causing the failure is ODF 4.19 specific:
https://issues.redhat.com/browse/DFBUGS-2244

Annette reports that deleting the VR manually cause clean to complete immediately.
