### ISSUE TITLE
Include the config file in command report

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#116]
When checking a report we want to have the tested configuration. We already log parts of the configuration, but it will be easier to debug issue if we always include the configuration with the report.

### Add the config to the report yaml

```yaml
config:
  clusters:
    hub:
      kubeconfig: ...
    c1:
      kubeconfig: ...
    c2:
      kubeconfig: ...
  drPolicy: ...
  clusterSet: ...
  pvcSpec:
  ...
  tests:
  ...
```

Since ramen/e2e/types has json tags, adding a Config to the report using ramne/e2e/types.Config should work.

This way the config is part of the run/clean yaml. If we change the config when running multiple commands the changes are reflected in the yaml for each command.

Issues:
- This makes the test report bigger.

### Copy the config file

Copy the config file to `outputdir/config.yaml`

This seems like the simplest and most direct way.

Issues:
- When running multiple steps with the same output directory, the config is copied over the previous config. If we changed the config in the latest run, the old config will be hidden.

## Implementation notes

We can copy the config by
- copying the file
- marshaling the config to yaml format

The second way will drop all the comments creating smaller file which may be easier to inspect.

We need for every command except init command, so it should be implemented by ramenctl/pkg/command package.

## Testing

1. Run a test
2. Check that the config used for the test is in `outputdir/config.yaml` or in the test report yaml, depending on how we implemented it.
