### ISSUE TITLE
Visualize entire system status

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#170]
We have multiple clusters and multiple components on each cluster. We need an easy way to show the status of the entire system. Quick look should show which components have issues (errors or warnings) and where they are located.

Based on the visualization you can continue to dig deeper using the resource collected during validation or or by inspecting the cluster.

We have 2 variants of the visualization:
- stdout: short version displayed by `ramenctl validate clusters`
- report: full version stored in the output directory in yaml format

## Example visualization

```yaml
clusters:
- hub1
  role: active hub
  drclusters:
  - ✅ dr1
  - ✅ dr2
  drpolicies:
  - ✅ dr-policy
  ramen:
  - ✅ config
  - ✅ operator
- dr1
  role: managed cluster
  ramen:
  - ✅ config
  - ✅ operator
  kube object protection:
  - ❌ backup
  - ❌ restore
  s3:
  - ❌ profile1 (inaccessible)
- dr2:
  role: managed cluster
  ramen:
  - ✅ config
  - ✅ operator
  kube object protection:
  - ✅ backup
  - ✅ restore
  s3:
  - ✅ profile2
```
