### ISSUE TITLE
Add gather report

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#179]
This issue is mostly about having a useful report that can be used my machines and humans to understand what was gathered and diagnose issues in the gather command.

The gather/report.go is similar to test/report but shows what we gathered. This is a yaml report which is both human an machine readable, describing all the details about the gather command.

The report is created `outdir/gather.yaml`.

Gather report add the following details to the generic report:

- application: name and namespace provided by the user
- namespaces: inferred from the drpc, gathered on all clusters
- clusters: the clusters we gathered from (name, status, duration)
- status: passed if all clusters gathered, failed if at least one failed
- duration: total time to gather from all clusters

Notes:
- The config for gather command does not care about pvcspecs, tests, channel. We may need to create a different type for parsing the config so we don't include unrelated stuff in the report.
- We can reuse code from test/report.go by moving it up to report/report.go.
- Depends on improving gather.Namespaces() #181 

Example report:

```yaml
application:
  name: my-app-drpc-1
  namespace: my-app
build:
  commit: 35215a24ec3a4759198b72a0e89358da62222a7f
  version: v0.5.1-25-g35215a2
config:
  clusterSet: default
  clusters:
    c1:
      kubeconfig: /home/nsoffer/.config/drenv/rdr/kubeconfigs/dr1
    c2:
      kubeconfig: /home/nsoffer/.config/drenv/rdr/kubeconfigs/dr2
    hub:
      kubeconfig: /home/nsoffer/.config/drenv/rdr/kubeconfigs/hub
  distro: k8s
  namespaces:
    argocdNamespace: argocd
    ramenDRClusterNamespace: ramen-system
    ramenHubNamespace: ramen-system
    ramenOpsNamespace: ramen-ops
created: "2025-05-15T17:25:29.351238314+03:00"
duration: 30.0
host:
  arch: amd64
  cpus: 10
  os: linux
name: gather
namespaces:
- ramen-system
- ramen-ops
- my-app
status: passed
clusters:
- duration: 10.0
  name: hub
  status: passed
- duration: 20.0
  name: dr1
  status: passed
- duration: 30.0
  name: dr2
  status: passed
```
