### ISSUE TITLE
Test run summary - host info

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#34]
When we debug issues with ramenctl command, it would be useful to have some info on the host running the command.

This should be part of the report yaml file. Every command should write a yaml file in standard format with all info about the host and ramenctl to make debugging issues easier.

```yaml
host:
  os: darwin
  arch: arm64
  version: "macOS 15.3.2"
ramenctl:
  version: v0.1.0
  commit: eb92ed81e2715d286bfd8ce173c76d4ecda9e2b4
```

Issues:
- Getting OS information probably requires os specific code. For now we will report it only if available via go standard library.
