### ISSUE TITLE
Test run summary - tests results

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#40]
When we finish to run the tests we want to have a machine and human readable summary of the test run. The summary should be written to the report directory.

Initial draft of the summary file:

```yaml
tests:
- workload: deploy
  deployer: appset
  pvcspec: rbd
  status: pass
- workload: deploy
  deployer: appset
  pvcspec: cephfs
  status: fail
```

### How to describe setup and cleanup

Test run contains:

1. Setup environment
2. Run tests

Test clean contains

1. Run clean
2. Clean environment

The report should describe this flow, including errors in test or in the setup/cleanup steps.

Test run:

```yaml
steps:
- name: setup
  status: passed
- name: tests
  tests:
  - workload: deploy
    deployer: appset
    pvcspec: rbd
    status: passed
  - workload: deploy
    deployer: appset
    pvcspec: cephfs
    status: passed
```

Test clean:

```yaml
steps:
- name: tests
  tests:
  - workload: deploy
    deployer: appset
    pvcspec: rbd
    status: passed
  - workload: deploy
    deployer: appset
    pvcspec: cephfs
    status: passed
- name: cleanup
  status: passed
```

See also #50 and #51
