### ISSUE TITLE
Add build infromation

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#46]
Keep git tag and commit hash in the built executable. We will use this to report the version in --version, and populate command report summary.

If build from a tag, it should report the tag:

```console
% ramenctl --version
v0.1.0
```

If built without the tag, show git description:

```console
% ramenctl --version
v0.4.0-20-g56935f2
```

If built without setting a version the version string will not be available.

The version will be in the command report:

```yaml
ramenctl:
  version: v0.1.0
  commit: eb92ed81e2715d286bfd8ce173c76d4ecda9e2b4
```
