### ISSUE TITLE
Add test steps to report

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#50]
We want to see the entire flow for each test run or clean.

For test run we always run the same flow, but we want to support running single step, or custom steps. In this case we want to see the actual flow without guessing what was tested. In all cases we want to know which step failed in the command failed.

For clean flow we always run the same flow and supporting single step or custom steps does not make sense, but we need to know which step failed if the command failed.

## Example for successful command

```yaml
- name: tests
  status: passed
  items:
  - config:
      deployer: appset
      pvcSpec: rbd
      workload: deploy
    name: appset-deploy-rbd
    status: passed 
    items:
    - name: deploy
      status: passed
    - name: protect
      status: passed
    - name: failover
      status: passed
    - name: relocate
      status: passed
    - name: unprotect
      status: passed
    - name: undeploy
      status: passed
```

## Example for failed command

```yaml
- name: tests
  status: failed
  - config:
      deployer: appset
      pvcSpec: rbd
      workload: deploy
    name: appset-deploy-rbd
    status: passed 
    items:
    - name: deploy
      status: passed
    - name: protect
      status: passed
    - name: failover
      status: failed
```
