### ISSUE TITLE
Add test report timing info

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#51]
When debugging tests it is helpful to see the time taken for every test step. We can compute this from log but this is hard and error prone.

We can add a time property to a test step reporting the time in seconds.

## Example test with timing

```yaml
- name: tests
  status: failed
  time: 670.70
  tests:
  - deployer: appset
    pvcSpec: rbd
    status: failed
    workload: deploy
    time: 670.70
    steps:
    - name: deploy
      status: passed
      time: 5.40
    - name: protect
      status: passed
      time: 126.50
    - name: failover
      status: passed
      time: 115.80
    - name: relocate
      status: failed
      time: 423.00s
```
