### ISSUE TITLE
Group preparation and cleanup steps

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#75]
Instead of adding new step for every operation we do before running the tests, group all the operations until a "prepare" step:

## Example test run

```console
🔎 Prepare for test ...
   ✅ Config validated
   ✅ Environment setup

🔎 Run tests ...
   ✅ Application "appset-deploy-rbd" deployed
   ✅ Application "appset-deploy-cephfs" deployed
   ✅ Application "appset-deploy-rbd" protected
   ✅ Application "appset-deploy-cephfs" protected
   ✅ Application "appset-deploy-cephfs" failed over
   ✅ Application "appset-deploy-rbd" failed over
   ✅ Application "appset-deploy-cephfs" relocated
   ✅ Application "appset-deploy-rbd" relocated
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed
```

## Example test run report

```yaml
steps:
- name: prepare
  status: passed
  items:
  - name: validate config
    stauts: passed
  - name: setup environment
    status: passed
- name: tests
  ...
```

## Example test clean

```console
🔎 Prepare for test ...
   ✅ Config validated

🔎 Clean tests ...
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed

🔎 Clean environment ...
   ✅ Environment cleanned
```

## Example test clean report

```yaml
steps:
- name: prepare
  status: passed
  items:
  - name: validate config
    stauts: passed
- name: tests
  ...
```
