### ISSUE TITLE
Support testing single step

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#78]
When debugging issues or developing tests, it is very useful to run a test flow up to a certain point and stop for inspecting the cluster. Then you may wan to continue run one of more steps and inspect the state of the system.

With go test this can be done using

```console
go test -run TestDR//Deploy
go test -run TestDR//Enable
go test -run TestDR//Failover
(inspect the system)
go test -run TestDR//Failover
(inspect the system)
```

We can provide an simpler and more power full way:

```console
ramenctl test run --steps deploy,protect,failover
(inspect the system)
ramenctl test run --steps failover
(inspect the system)
```

The implementation can be very simple - we have a static test flow that can be converted to running list of steps by name. Then we can run the requested steps form --steps instead of the static flow.

Issues:
- When using the same output direcotory, test-run.* files will overwrite previous runs. We need to keep all logs and reports so we have complete picture of what was happened.

**Comment by raghavendra-talur** [comment]
I like this feature. Based on this idea, I think we should also make the DRWorkflow config driven in the ramen e2e. Like you say, it is just a sequence of steps and requires not much code change.

**Comment by nirs** [comment]
> I like this feature. Based on this idea, I think we should also make the DRWorkflow config driven in the ramen e2e. Like you say, it is just a sequence of steps and requires not much code change.

The current code (disapp) does not support yet arbitrary flow, but once we fix it we can keep several flows like:

```yaml
flows:
- name: quick
  steps:
  - deploy
  - protect
  - failover
  - relocate
  - unprotect
  - undeploy
- name: full
  steps:  
  - deploy
  - protect
  - failover
  - unprotect
  - protect
  - relocate
  - relocate
  - failover
  - failover
  - unprotect
  - undeploy
```

And add:

```console
ramenctl test run --flow full
```
