### ISSUE TITLE
init: Use better defaults when running as `odf dr`

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#83]
When we run as `odf dr` we can use better defaults for ODF to minimize manual and error prone changes.

## pvcSpecs

This works in ODF:

```yaml
- name: rbd
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes: ReadWriteOnce
- name: cephfs
  storageClassName: ocs-storagecluster-cephfs
  accessModes: ReadWriteMany
```

## Detecting that we run as `odf dr`

Can use:

```go
if RootCmd.Use == "dr" {
    // running as odf dr...
}
```

This will make it harder to use `odf dr` with k8s cluster, but in this case one should use ramenctl.

## Changes

- Add RBDStorageClassName and CephFSStorageClassName to Sample
- Add defaults for k8s and odf
- Use the best default for `RootCmd.Use`
