### ISSUE TITLE
config: Configurable test flows

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#84]
The current code (disapp) does not support yet arbitrary flow, but once we fix it we can keep several flows. This can be useful to run quicker tests for every pr, and cover more code in nightly or manual tests.

## Example flows

```yaml
flows:
- name: quick
  steps:
  - deploy
  - protect
  - failover
  - relocate
  - unprotect
  - undeploy
- name: full
  steps:  
  - deploy
  - protect
  - failover
  - unprotect
  - protect
  - relocate
  - relocate
  - failover
  - failover
  - unprotect
  - undeploy
```

## Example usage

```console
ramenctl test run --flow full
```

Created from [#78](https://github.com/RamenDR/ramenctl/issues/78#issuecomment-2758634222)
