### ISSUE TITLE
init: Generate test matrix

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramenctl#86]
Using ramenctl init we get one test. For testing changes to ramen I usually want to have the full test matrix:

```yaml
tests:
- workload: deploy
  deployer: appset
  pvcSpec: rbd 
- workload: deploy
  deployer: appset
  pvcSpec: cephfs
- workload: deploy
  deployer: subscr
  pvcSpec: rbd 
- workload: deploy
  deployer: subscr
  pvcSpec: cephfs
- workload: deploy
  deployer: disapp
  pvcSpec: rbd 
- workload: deploy
  deployer: disapp
  pvcSpec: cephfs                                                                                                                                                                                                
```

Maybe add --deployers and --pvc-specs arguemnt, so we can use this command to get the full matrix:

```console
ramenctl init --deployers appset,subscr,disapp --pvc-specs rbd,cephfs
```

Adding arguemnts and validating arguments is trivial. Building the test matrix is also very easy. The problem is how to build the test matrix with the yaml template.

I think what can work is to build the test matrix, marshal it to yaml and inject the yaml into the template so we can keep the comments.

Another way is to learn how to parse the yaml keeping the comments (like limayaml), so we can operate on the config model instead of template.
